# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Perf auditing
env:
  # Netlify builds PRs with name deploy-preview-${PR number}
  COMMIT_PREVIEW_URL: "https://deploy-preview-${{ github.event.number }}--ccm-main-gatsby.netlify.app"
on:
  pull_request:
    branches: [ master ]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        # Netlify builds the commit at the tip of the PR branch. However by
        # default this action checks out the merge commit created by github.
        # So here we force it to check out the commit at the tip of the PR branch.
        with:
          ref: ${{ github.head_ref }}
      - run: ./scripts/wait_for_url.sh "${COMMIT_PREVIEW_URL}/__buildmeta/$(git rev-parse HEAD)"
        timeout-minutes: 10
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: ${{ env.COMMIT_PREVIEW_URL }}
          runs: 3
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
