# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Perf auditing
env:
  # Netlify builds PRs with name deploy-preview-${PR number}
  COMMIT_PREVIEW_URL: "https://deploy-preview-${{ github.event.number }}--ccm-main-gatsby.netlify.app"
on:
  pull_request:
    branches: [ master ]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        # Netlify builds the commit at the tip of the PR branch. However by
        # default this action checks out the merge commit created by github.
        # So here we force it to check out the commit at the tip of the PR branch.
        with:
          ref: ${{ github.head_ref }}
      - run: ./scripts/wait_for_url.sh "${COMMIT_PREVIEW_URL}/__buildmeta/$(git rev-parse HEAD)"
        timeout-minutes: 10
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }}
          branch: ${{ github.ref }}
          outputDirectory: /tmp/artifacts
          urls: ${{ env.COMMIT_PREVIEW_URL }}
          sha: $(git rev-parse HEAD)
          prCommentSaveOld: true
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
